baseURL = "https://max-inden.de/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mxinden"
theme = "ezhil"
enableGitInfo = false

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
subtitle = "Homepage of Max Inden"
homeMetaContent = ""
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
# For more date formats see https://gohugo.io/functions/format/
dateFormat = "Jan 2, 2006"
mainSections = ["posts"]

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mxinden"

[[menu.main]]
name = "Tags"
url = "/tags"

[markup]
  [markup.highlight]
    style = "bw"
