baseURL = "https://mxinden.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mxinden"
theme = "cupper-hugo-theme"
enableGitInfo = false

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Homepage of Max Inden"
  homeMetaContent = ""
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  # codePenUser = "someUser"
  # katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Talks"
    url = "/talks/"
    weight = 3
  [[menu.nav]]
    name = "Resume"
    url = "/resume/"
    weight = 4
  [[menu.nav]]
    name = "Misc"
    url = "/misc/"
    weight = 5
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 6
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 7
